# Generated by Django 5.2.14 on 2026-05-26 12:42

import django.db.models.deletion
import saved_queries.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(max_length=255)),
                ('selected_fields', models.JSONField(blank=True, default=saved_queries.models._default_fields)),
                ('search_field', models.CharField(blank=True, default='', max_length=255)),
                ('query', models.CharField(blank=True, default='', max_length=255)),
                ('limit', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='instances.odooinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_query_name_per_user')],
            },
        ),
    ]
