# Generated by Django 5.2.14 on 2026-05-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('odoo_url', models.URLField(max_length=300)),
                ('database', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=200)),
                ('encrypted_password', models.TextField()),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('auth_failed', 'Authentication failed'), ('connection_failed', 'Connection failed'), ('error', 'Error')], default='unknown', max_length=32)),
                ('last_connection_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_instance_name_per_user')],
            },
        ),
    ]
